### 어떤 영화가 좋은 평점을 받았는지 분석

In [1]:
import numpy as np

#### 1. 데이터 불러오기

In [10]:
# genfromtxt
# np.genfromtxt('파일경로', delimiter = '구분자::', dtype = 데이터 타입)

movie = np.genfromtxt('data/ratings.dat', delimiter ='::', dtype =np.int64)

movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [16]:
# 데이터 저장
# np.savetxt('파일경로',데이터,delimiter='구분자',fmf='자료형')

np.savetxt('data/temp.txt',movie,delimiter=':',fmt='%d')

### 1. 각 열
- 0번 인덱스 열 : 사용자의 id
- 1번 인덱스 열 : 영화의 id
- 2번 인덱스 열 : 영화의 평점
- 3번 인덱스 열 : 리뷰 입력 시간

### 2. 데이터의 속성 확인
- 배열 형태
- 배열 차원 수
- 배열 전체 요소 수

In [20]:
print(movie.shape)
print(movie.ndim)
print(movie.size)

(1000209, 4)
2
4000836


### 3. 전체 영화들의 평점의 평균 구하기

In [24]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [32]:
# 전체 영화들의 평점에 접근
# 2차원 배열에서의 데이터 접근 [ 행의 범위 , 열의 범위 ]
ratings = movie[:,2]
ratings

array([5, 3, 3, ..., 5, 4, 4], dtype=int64)

In [36]:
# 전체 영화들의 평점의 평균
ratings.mean()

3.581564453029317

In [38]:
np.mean(ratings)

3.581564453029317

In [40]:
round(ratings.mean(),2) # 소수점 2째자리까지 출력

3.58

#### 4. ID가 1인 사용자가 매긴 영화들의 평점들의 평균

In [42]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [53]:
# boolean 인덱싱 : 특정 조건에 맞는 데이터를 가져올 때
# 아이디가 1인 사용자가 매긴 영화데이터
ID_1 = movie[:,0]==1
ID_1

array([ True,  True,  True, ..., False, False, False])

In [106]:
# 불리언 인덱싱
# ID가 1인 데이터를 가져오기

ID_1 = movie[movie[:,0]==1]
ID_1

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [108]:
# ID가 1인 사람의 영화데이터'의' 평점을 가져오기

ID_1_rating = ID_1[:,2]
ID_1_rating

array([5, 3, 3, 4, 5, 3, 5, 5, 4, 4, 5, 4, 4, 4, 5, 4, 3, 4, 5, 4, 3, 3,
       5, 5, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       4, 5, 5, 4, 5, 4, 4, 4, 4], dtype=int64)

In [ ]:
# ID가 1인 사람의 영화데이터'의' 평점들'의' 평균
ID_1_rating.mean()

In [77]:
# 중간에 변수로 만드는 과정 없이
movie[movie[:,0]==1][:,2].mean()

4.188679245283019

### 각 사용자가 매긴 평점들의 평균

In [89]:
movie[movie[:,0]==1][:,2].mean()
movie[movie[:,0]==2][:,2].mean()
movie[movie[:,0]==3][:,2].mean()
movie[movie[:,0]==4][:,2].mean()


4.190476190476191

In [142]:
# 데이터의 유효성 검사(6040가지 인지)
# 1~6040

# 중복값을 제거해주는(유일한 값들만 구해주는) 함수
# np.unique(시퀀스 자료형)

user_id = np.unique(movie[:,0])

user_id

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [144]:
len(user_id)

6040

In [148]:
# 오름차순 sort()
np.sort(user_id)

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [150]:
# 내림차순
np.sort(user_id)[::-1]

array([6040, 6039, 6038, ...,    3,    2,    1], dtype=int64)

In [154]:
# 전체 아이디의 수
user_id.size

6040

In [247]:
user_mean_list = []
for i in user_id:
    user_mean = movie[movie[:,0]==i][:,2].mean() # 사용자별로 영화 평점의 평균을 나타내는 user_mean
    user_mean_list.append([i,user_mean])
user_mean_list

[[1, 3.7131782945736433],
 [2, 3.9019607843137254],
 [3, 4.190476190476191],
 [4, 3.1464646464646466],
 [5, 3.9014084507042255],
 [6, 4.32258064516129],
 [7, 3.884892086330935],
 [8, 3.7358490566037736],
 [9, 4.114713216957606],
 [10, 3.2773722627737225],
 [11, 3.8260869565217392],
 [12, 3.388888888888889],
 [13, 3.32],
 [14, 3.3233830845771144],
 [15, 3.0285714285714285],
 [16, 4.075829383886256],
 [17, 3.6491803278688524],
 [18, 3.5725490196078433],
 [19, 4.083333333333333],
 [20, 2.909090909090909],
 [21, 3.0673400673400675],
 [22, 3.3157894736842106],
 [23, 3.948529411764706],
 [24, 3.7411764705882353],
 [25, 2.96],
 [26, 4.171428571428572],
 [27, 3.7570093457943927],
 [28, 3.5833333333333335],
 [29, 3.488372093023256],
 [30, 3.73109243697479],
 [31, 3.625],
 [32, 3.498721227621483],
 [33, 3.8658536585365852],
 [34, 3.54040404040404],
 [35, 4.199430199430199],
 [36, 3.69811320754717],
 [37, 3.58],
 [38, 3.564516129032258],
 [39, 3.4479166666666665],
 [40, 3.48],
 [41, 3.74025974025

### 6. 각 사용자별 평균 평점이 4점 이상인 사용자만 구해보기

In [ ]:
# 리스트 > 배열
# 조건문 적어서 불리언 인덱싱

In [172]:
user_mean_arr = np.array(user_mean_list)

user_mean_arr

array([[1.00000000e+00, 3.71317829e+00],
       [2.00000000e+00, 3.90196078e+00],
       [3.00000000e+00, 4.19047619e+00],
       ...,
       [6.03800000e+03, 3.87804878e+00],
       [6.03900000e+03, 3.57771261e+00],
       [6.04000000e+03,            nan]])

In [174]:
# set_printoptions : numpy 배열 출력시 출력 형태를 설정하는 함수
# suppress=True : 소수점 자리수 고정 출력 선언
# precision=2 : 소수점 둘째짜리까지
np.set_printoptions(suppress=True, precision=2)

In [176]:
user_mean_arr

array([[   1.  ,    3.71],
       [   2.  ,    3.9 ],
       [   3.  ,    4.19],
       ...,
       [6038.  ,    3.88],
       [6039.  ,    3.58],
       [6040.  ,     nan]])

In [182]:
user_mean_arr[user_mean_arr[:,1]>=4]

array([[   3.  ,    4.19],
       [   6.  ,    4.32],
       [   9.  ,    4.11],
       ...,
       [6026.  ,    4.25],
       [6031.  ,    4.13],
       [6033.  ,    4.1 ]])

In [192]:
user_mean_4 = user_mean_arr[user_mean_arr[:,1]>=4]
user_mean_4

array([[   3.  ,    4.19],
       [   6.  ,    4.32],
       [   9.  ,    4.11],
       ...,
       [6026.  ,    4.25],
       [6031.  ,    4.13],
       [6033.  ,    4.1 ]])

In [188]:
user_mean_4[:,0]

array([   3.,    6.,    9., ..., 6026., 6031., 6033.])

In [196]:
user_mean_arr[user_mean_arr[:,1]>=4][:,0].astype(int)

array([   3,    6,    9, ..., 6026, 6031, 6033])

### 7. 10번 영화의 평점의 평균을 구하라

In [ ]:
# 조건 '10번 영화' '평점' '평균'

In [201]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [203]:
rating_10 = movie[movie[:,1]==10] # 영화id가 10인 리스트 추출
rating_10

array([[       13,        10,         3, 978201884],
       [       18,        10,         5, 978153344],
       [       19,        10,         5, 978147137],
       ...,
       [     6016,        10,         4, 956777700],
       [     6019,        10,         3, 956761104],
       [     6027,        10,         5, 956726620]], dtype=int64)

In [211]:
rating_10_mean=rating_10[:,2] # 영화 10번의 평점

In [217]:
rating_10_mean.mean() # 10번 영화의 평점의 평균

3.5405405405405403

In [221]:
round(movie[movie[:,1]==10][:,2].mean(),4) # 요약 ++ round 소수점 넷째자리까지

3.5405

### 8. 각 영화가 받은 평점의 평균 구하기

In [ ]:
#영화별 평점. 평균

In [223]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [253]:
movie_num=np.unique(movie[:,1])

In [255]:
movie_num # 각 영화

array([   1,    2,    3, ..., 3950, 3951, 3952], dtype=int64)

In [275]:
# 각 영화의 평점
movie_mean_list=[]
for i in movie_num:
    movie_mean = movie[movie[:,1]==i][:,2].mean()
    movie_mean_list.append([i,movie_mean])
movie_mean_list

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566],
 [6, 3.8787234042553194],
 [7, 3.410480349344978],
 [8, 3.014705882352941],
 [9, 2.656862745098039],
 [10, 3.5405405405405403],
 [11, 3.7938044530493706],
 [12, 2.3625],
 [13, 3.2626262626262625],
 [14, 3.542483660130719],
 [15, 2.458904109589041],
 [16, 3.7932551319648096],
 [17, 4.027544910179641],
 [18, 3.337579617834395],
 [19, 2.480719794344473],
 [20, 2.5375],
 [21, 3.6238938053097347],
 [22, 3.3492063492063493],
 [23, 2.857142857142857],
 [24, 3.1794871794871793],
 [25, 3.6510204081632653],
 [26, 3.53],
 [27, 2.9344262295081966],
 [28, 4.055865921787709],
 [29, 4.062034739454094],
 [30, 3.6486486486486487],
 [31, 3.1134751773049647],
 [32, 3.945731303772336],
 [33, 3.0],
 [34, 3.8914905768132497],
 [35, 3.3142857142857145],
 [36, 3.9579741379310347],
 [37, 3.5],
 [38, 2.8214285714285716],
 [39, 3.6233480176211454],
 [40, 3.933333333333333],
 [41, 3.9586776